/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author RPL
 */
public class Masakan extends javax.swing.JFrame {

    /**
     * Creates new form Masakan
     */
    public Masakan() {
        initComponents();
        super.setTitle("Kasir Restaurant");
        this.setLocationRelativeTo(null);
        tabel.setModel(tblModel);
        Tabel(tabel, new int[]{160,160,160,160,160});
        setDefaultTable();
        Awal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        id = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        pencarian = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jenkel = new javax.swing.JComboBox<>();
        alamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(826, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(160, 10, 130, 30);

        nik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nikKeyTyped(evt);
            }
        });
        getContentPane().add(nik);
        nik.setBounds(160, 50, 130, 30);

        nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaKeyTyped(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(160, 100, 130, 30);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(500, 80, 480, 110);

        pencarian.setToolTipText("Pencarian Berdasarkan Nama");
        pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pencarianKeyReleased(evt);
            }
        });
        getContentPane().add(pencarian);
        pencarian.setBounds(810, 30, 130, 30);

        jLabel8.setText("Cari");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(770, 20, 30, 30);

        simpan.setText("Simpan");
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(150, 430, 100, 50);

        tambah.setText("Tambah");
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(30, 430, 100, 50);

        ubah.setText("Ubah");
        ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah);
        ubah.setBounds(390, 430, 110, 50);

        hapus.setText("Hapus");
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(270, 430, 110, 50);

        batal.setText("Batal");
        batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal);
        batal.setBounds(510, 430, 100, 50);

        jenkel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Kelamin", "Laki - Laki", "Perempuan" }));
        getContentPane().add(jenkel);
        jenkel.setBounds(260, 320, 120, 25);
        getContentPane().add(alamat);
        alamat.setBounds(170, 150, 230, 160);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 500);

        setBounds(0, 0, 1015, 536);
    }// </editor-fold>//GEN-END:initComponents

    private void hub(String sql){
        try {
            String hubung="jdbc:mysql://localhost:3306/perjalanan_catatan";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon=DriverManager.getConnection(hubung,"root","");
            Statement stt=kon.createStatement();
            stt.executeUpdate(sql);
            stt.close();
            kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
        
    }
    
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
    
    private void Tabel(javax.swing.JTable tb, int lebar[]) {
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for(int i=0;i<kolom;i++) {
            javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(17);
        }
    }
    
    private javax.swing.table.DefaultTableModel getDefaultTabelModel() {
        return new javax.swing.table.DefaultTableModel(
                new Object [][]{},
                new String []{"ID","NIK","NAMA","ALAMAT","JENKEL"}
        ){
        boolean[] canEdit = new boolean []{
            false,false,false
        };
        public boolean isCellEditable(int rowIndex, int columnIndex){
            return canEdit [columnIndex];
        }
        };
                }
    
    String data[]=new String[5];
    public void setDefaultTable() {
        try{
            String hubung = "jdbc:mysql://localhost:3306/perjalanan_catatan";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "select * from tb_pengguna where nik like '%"+pencarian.getText()+"%'";
            ResultSet res = stt.executeQuery(SQL);
            tblModel.setRowCount(0);
        while(res.next()){
            data[0] = res.getString(1);
            data[1] = res.getString(2);
            data[2] = res.getString(3);
            data[3] = res.getString(4);
            data[4] = res.getString(5);
            tblModel.addRow(data);
        }
            res.close();
            stt.close();
            kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
            JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
        }
    }
    
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        nik.requestFocus();
        
        nik.setEnabled(true);
        nama.setEnabled(true);
        alamat.setEnabled(true);
        jenkel.setEnabled(true);
        
        tambah.setEnabled(false);
        simpan.setEnabled(true);
        batal.setEnabled(true);
        
        Kode();
    }//GEN-LAST:event_tambahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try{
            String SQL = "insert into tb_pengguna values('"+id.getText()+"','"+nik.getText()+"','"+nama.getText()+"','"+alamat.getText()+"','"+jenkel.getSelectedItem()+"')";
            hub(SQL);
            setDefaultTable();
            Awal();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
        }catch(Exception exc){
            System.err.println(exc.getMessage());
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!");
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        try{
            String SQL = "update tb_pengguna set nik = '"+nik.getText()+"', nama = '"+nama.getText()+"' where id_pengguna = '"+id.getText()+"'";
            hub(SQL);
            setDefaultTable();
            Awal();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
        }catch(Exception exc) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try{
            String SQL = "delete from tb_pengguna where id_pengguna='"+id.getText()+"'";
            hub(SQL);
            setDefaultTable();
            Awal();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
        }catch(Exception exc){
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus!");
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        Awal();
    }//GEN-LAST:event_batalActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            Tampil();
            
            tambah.setEnabled(false);
            simpan.setEnabled(false);
            ubah.setEnabled(true);
            hapus.setEnabled(true);
            batal.setEnabled(true);
        
            nik.setEnabled(true);
            nama.setEnabled(true);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void pencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianKeyReleased
        // TODO add your handling code here:
        setDefaultTable();
    }//GEN-LAST:event_pencarianKeyReleased

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
        if (id.getText().length() == 4){
            evt.consume(); 
        }
    }//GEN-LAST:event_idKeyTyped

    private void nikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nikKeyTyped
        // TODO add your handling code here:
        if (nik.getText().length() == 30){
            evt.consume(); 
        }
    }//GEN-LAST:event_nikKeyTyped

    private void namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaKeyTyped
        // TODO add your handling code here:
        if (nama.getText().length() == 6){
            evt.consume(); 
        }
    }//GEN-LAST:event_namaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masakan().setVisible(true);
            }
        });
    }
    
    public void Awal(){
        id.setEnabled(false);
        nik.setEnabled(false);
        nama.setEnabled(false);
        alamat.setEnabled(false);
        jenkel.setEnabled(false);
        
        tambah.setEnabled(true);
        simpan.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        batal.setEnabled(false);
        
        id.setText("");
        nik.setText("");
        nama.setText("");
        alamat.setText("");
    }
    
    public void Kode(){        
        try{
            String hubung = "jdbc:mysql://localhost:3306/perjalanan_catatan";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stmt = kon.createStatement();
            String SQL = "select max(right(id_pengguna,2)) as NO from tb_pengguna";
            ResultSet rs = stmt.executeQuery(SQL);
            while(rs.next())
            {
                if(rs.first() == false)
                {
                    id.setText("IM0");
                }
                else
                {
                   rs.last();
                   int auto = rs.getInt(1) + 1;
                   String NO = String.valueOf(auto);
                   int noLong = NO.length();
                   for(int a=0;a<2-noLong;a++)
                    { 
                        NO = "IM0" + NO;
                    }
                   id.setText(NO);
                
                 }        
            }
            rs.close();
            stmt.close();
            }    
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                            "Kesalahan", JOptionPane.WARNING_MESSAGE);

        }
    }
    
    int row = 0;
    public void Tampil(){
        row = tabel.getSelectedRow();
        id.setText(tblModel.getValueAt(row,0).toString());
        nik.setText(tblModel.getValueAt(row,1).toString());
        nama.setText(tblModel.getValueAt(row,2).toString());
        alamat.setText(tblModel.getValueAt(row,3).toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton batal;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenkel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField pencarian;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
